#!/bin/bash
tput setaf 2
echo "=================="
echo "|  Starting SSH  |"
echo "=================="
#sudo systemctl start sshd.service
sudo systemctl enable sshd
sudo systemctl start sshd
echo "ssh user@host or user@ip"
#sudo systemctl restart sshd