#!/bin/bash
#
# Copyright (C) 2017-2018 Matthew Keller
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# Dependencies: spotify and mpris-ctl
# Usage       : ./spotify next(nt) or prev(pt)
# Calls on system link to Spotify
#
normal=$(tput sgr0)              # White
red=$(tput setaf 1)              # Red
green=$(tput setaf 2)            # Green
yellow=$(tput setaf 3)           # Yellow
blue=$(tput setaf 21)            # Blue
violet=$(tput setaf 5)           # Violet
cyan=$(tput setaf 6)             # Cyan
white=$(tput setaf 7)            # White
bldred=${txtbld}$(tput setaf 1)  # Bold Red
bldgrn=${txtbld}$(tput setaf 2)  # Bold Green
bldblu=${txtbld}$(tput setaf 21) # Bold Blue
bldylw=${txtbld}$(tput setaf 3)  # Bold Yellow
bldvlt=${txtbld}$(tput setaf 5)  # Bold Violet
bldcya=${txtbld}$(tput setaf 6)  # Bold Cyan
bldwht=${txtbld}$(tput setaf 7)  # Bold White
blink=$(tput blink)              # Blink
bold=$(tput bold)                # Bold
reverse=$(tput smso)             # Reverse Colors
underline=$(tput smul)           # Underline

pause(){
  tput setaf 38
  read -p "Press [Enter] key to continue..." fackEnterKey
}

show_main_menu() {
tput setaf 38
    clear
    	  echo ${green}""
		  echo "==============================="
          echo "|            Spotify          |"
          echo "==============================="
mpris-ctl info "   Artist   : %artist_name"  
mpris-ctl info "   Track    : %track_name"
mpris-ctl info "   Length   : %track_length"
mpris-ctl info "   Shuffle  : %shuffle"
          echo "==============================="
          echo "| [1] Next                    |" 
          echo "| [2] Previous                |"
          echo "==============================="
read menu
case $menu in
1|next)
	clear
	mpris-ctl next
	echo ${green}""
		  echo "==============================="
          echo "|            Spotify          |"
          echo "==============================="
mpris-ctl info "   Artist   : %artist_name"  
mpris-ctl info "   Track    : %track_name"
mpris-ctl info "   Length   : %track_length"
          echo "==============================="
          echo "| [1] Next                    |" 
          echo "| [2] Previous                |"
          echo "==============================="
;;
2|previous)
	mpris-ctl previous
	echo ${green}""
		  echo "==============================="
          echo "|            Spotify          |"
          echo "==============================="
mpris-ctl info "   Artist   : %artist_name"  
mpris-ctl info "   Track    : %track_name"
mpris-ctl info "   Length   : %track_length"
          echo "==============================="
          echo "| [1] Next                    |" 
          echo "| [2] Previous                |"
          echo "==============================="
;;
a|A|about)
    clear
    tput setaf 1
    echo ""
    echo " This is a Script Made to Customize Arch Linux"
    echo "   Written by Matthew Keller [KillerDroid96]"
    echo ""
    echo " Type bl (bash list) to diplay custom commands"
    echo ""
    tput setaf 36
    pause
    $HOME/Github/Scripts/Linux/Shells/shell_list
    pause
    clear
    show_main_menu
;;
Help|help|h|H)
    clear
    tput setaf 1
    echo ""
    echo "To Use Menu Enter the Number or Letter"
    echo ""
    tput setaf 36
    pause
    clear
    show_main_menu
;;
Exit|e|E|exit)
    clear
    exit 0
;;
*)
echo don\'t know
;;
esac

}

while true
do
    show_main_menu
    
done 