#!/bin/bash
normal=$(tput sgr0)              # White
red=$(tput setaf 1)              # Red
green=$(tput setaf 2)            # Green
yellow=$(tput setaf 3)           # Yellow
blue=$(tput setaf 21)            # Blue
violet=$(tput setaf 5)           # Violet
cyan=$(tput setaf 6)             # Cyan
white=$(tput setaf 7)            # White
bldred=${txtbld}$(tput setaf 1)  # Bold Red
bldgrn=${txtbld}$(tput setaf 2)  # Bold Green
bldblu=${txtbld}$(tput setaf 21) # Bold Blue
bldylw=${txtbld}$(tput setaf 3)  # Bold Yellow
bldvlt=${txtbld}$(tput setaf 5)  # Bold Violet
bldcya=${txtbld}$(tput setaf 6)  # Bold Cyan
bldwht=${txtbld}$(tput setaf 7)  # Bold White
blink=$(tput blink)              # Blink
bold=$(tput bold)                # Bold
reverse=$(tput smso)             # Reverse Colors
underline=$(tput smul)           # Underline

echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"##########                                                             ##########"
echo -e ${blue}"##########  ########  ######## ##     ## ######## ########   #######   ##########"
echo -e ${blue}"##########  ##     ## ##        ##   ##     ##    ##     ## ##     ##  ##########"
echo -e ${blue}"##########  ##     ## ##         ## ##      ##    ##     ## ##     ##  ##########"
echo -e ${blue}"##########  ##     ## ######      ###       ##    ########  ##     ##  ##########"
echo -e ${blue}"##########  ##     ## ##         ## ##      ##    ##   ##   ##     ##  ##########"
echo -e ${blue}"##########  ##     ## ##        ##   ##     ##    ##    ##  ##     ##  ##########"
echo -e ${blue}"##########  ########  ######## ##     ##    ##    ##     ##  #######   ##########"
echo -e ${blue}"##########                                                             ##########"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"##########                                                             ##########"
echo -e ${blue}"##########   $red "WARNING: Dextroamphetamine is a CPU stimulant!"        ${blue}   ##########"
echo -e ${blue}"##########   $red "WARNING: Dextroamphetamine may cause dizziness!"       ${blue}   ##########"
echo -e ${blue}"##########   $red "WARNING: Dextroamphetamine may cause sleeplessness!"   ${blue}   ##########"
echo -e ${blue}"##########   $red "WARNING: Dextroamphetamine is to be used only by you!" ${blue}   ##########"
echo -e ${blue}"##########   $red "WARNING: Use Dextroamphetamine with extreme caution!"  ${blue}   ##########"
echo -e ${blue}"##########                                                             ##########"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"
echo -e ${blue}"#################################################################################"${white}

# Source our universal functions script and macOS check
source $HOME/Github/nathan_scripts/common

TG=true
TG_MSG_FILE=/tmp/tg-msg.build-rom

if [[ ${TG} ]]; then
    {
        echo "\`\`\`"
        echo "Currently Executing..."
        echo "$(basename "${0}") ${PARAMS}"
        echo "\`\`\`"
    } > ${TG_MSG_FILE}
    notify "$(cat ${TG_MSG_FILE})"
fi

function build() {
clear
header "SETTING UP BUILD ENVIRONMENT"

# Check and see if we are on Arch
# If so, activare a virtual environment for proper Python support
[[ -f /etc/arch-release ]] && mkavenv
    source build/envsetup.sh

header "SYNCING LATEST SOURCES"; echo
    #repo sync "${JOBS_FLAG}" --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune
    repo sync -j$( nproc --all ) --force-broken --force-sync --current-branch --no-clone-bundle --no-tags --prune --optimized-fetch 

header "PREPARING $(echo ${DEVICE} | awk '{print toupper($0)}')"
     ${DEVICE}

header "CLEANING UP OUT DIRECTORY"
    m BUILD_TYPE

header "MAKING FILES"; echo
    m -j$( nproc --all ) ${MAKE_TARGET}
}


PS3=header'Choose Build type: ' 
options=(${green}"Clean"${white} ${yellow}"Dirty"${white} ${red}"Exit"${white})

select opt in "${options[@]}"
do 
    case $opt in
    "${green}Clean${white}")
        echo ""
        echo "${green}Clean Build${white}"
        BUILD_TYPE=clobber
        clear
        break
        ;;
    "${yellow}Dirty${white}")
        echo ""
        clear
        echo "${yellow}Dirty Build${white}"
        BUILD_TYPE=
        clear 
        break
        ;;
    "${red}Exit${white}")
        break
        ;;
        *) echo invalid option;;
    esac
done

if [[ DEVICE ]]; then
header "Select Device to Build"
PS2='Build: '
options=("OnePlus 5T" "Nexus 6P" "Galaxy S4" ${red}"Exit"${white})
select opt in "${options[@]}"
do
    case $opt in
    "OnePlus 5T")
        MAKE_TARGET=lunch
        DEVICE=dumpling
        build
        clear
        break
        ;;
    "Nexus 6P")
        MAKE_TARGET=breakfast
        DEVICE=angler
        build
        break
        ;;
    "Galaxy S4")
        MAKE_TARGET=lunch
        DEVICE=jfltespr
        build
        break
        ;;
    "${red}Exit${white}")
        break
        ;;
        *) echo invalid option;;
    esac
  done
fi