#!/usr/bin/env bash

# Source our universal functions script and macOS check
source $HOME/Github/nathan_scripts/common

echo "${GRN}KillerDroid96/android_build"
cd $HOME/Github/DU/build
git remote add kd git@github.com:KillerDroid96/android_build.git 
git remote add du git@github.com:DirtyUnicorns/android_build.git 
git checkout o8x-caf 
git pull kd o8x-caf 
git pull du o8x-caf
git push --set-upstream kd o8x-caf

echo "KillerDroid96/android_frameworks_base"
cd $HOME/Github/DU/frameworks/base
git remote add kd git@github.com:KillerDroid96/android_frameworks_base.git 
git remote add du git@github.com:DirtyUnicorns/android_frameworks_base.git 
git checkout o8x-caf 
git pull kd o8x-caf 
git pull du o8x-caf
git push --set-upstream kd o8x-caf

echo "KillerDroid96/android_device_oneplus_msm8998-common"
cd $HOME/Github/DU/device/oneplus/msm8998-common
git remote add kd git@github.com:KillerDroid96/android_device_oneplus_msm8998-common.git 
git remote add du git@github.com:DirtyUnicorns/android_device_oneplus_msm8998-common.git 
git checkout o8x-caf 
git pull kd o8x-caf
git pull du o8x-caf 
git push --set-upstream kd o8x-caf

echo "KillerDroid96/flash_kernel_oneplus_msm8998"
cd $HOME/Github/DU/kernel/oneplus/msm8998
git remote add kd git@github.com:KillerDroid96/flash_kernel_oneplus_msm8998.git 
git remote add nc git@github.com:nathanchance/op5.git 
git checkout -b 8.1.0 
git checkout 8.1.0 
git pull kd 8.1.0
git pull nc 8.1.0-unified
git push --set-upstream kd 8.1.0