#!/usr/bin/env bash
source build/envsetup.sh

echo ""
echo "#############"
echo "# REPO SYNC #"
echo "#############"
echo "Sync Repo?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) time repo sync --force-sync; break;;
        No ) break;;
    esac
done

############
# REPOPICK #
############
header "REPO PICK"
echo "Do you have any changes to pick?"
select yn in "Yes" "No"; do
    case $yn in
        Yes )   repopick 225213
                repopick 225475
                repopick 225476
                repopick 226402
                repopick 225506
                repopick 225507
                repopick 223374
                repopick 223410
                repopick 224945
                repopick 224946
                repopick 224948
                repopick 224949
                repopick 224950
                repopick 224951
                repopick 224952
                repopick 224953
                repopick 224954
                repopick 233465
                repopick 228566
                repopick 228569
                repopick 228570
                repopick 228571
                repopick 228572
                repopick 228576
                repopick 228578
                repopick 228580
                repopick 228582
                repopick 228583
                repopick 228584
                repopick 228585 
                repopick 228586
                repopick 225499
                repopick 226109
                repopick 226110
                repopick 226127
                repopick 226111
                repopick 229304
                repopick 226128
                repopick 226129
                repopick 226130
                repopick 229125
                repopick 224752
                repopick 226638
                repopick 226643
                repopick 227260
                repopick 227261; break;;
        No ) break;;
    esac
done

echo ""
echo "Now brunch <device>"