#!/bin/bash
#
# Copyright (C) 2017-2018 Matthew Keller
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
RED='\033[0;41;30m'
STD='\033[0;0;39m'
normal=$(tput sgr0)              # White
red=$(tput setaf 1)              # Red
green=$(tput setaf 2)            # Green
yellow=$(tput setaf 3)           # Yellow
blue=$(tput setaf 21)            # Blue
violet=$(tput setaf 5)           # Violet
cyan=$(tput setaf 6)             # Cyan
white=$(tput setaf 7)            # White
bldred=${txtbld}$(tput setaf 1)  # Bold Red
bldgrn=${txtbld}$(tput setaf 2)  # Bold Green
bldblu=${txtbld}$(tput setaf 21) # Bold Blue
bldylw=${txtbld}$(tput setaf 3)  # Bold Yellow
bldvlt=${txtbld}$(tput setaf 5)  # Bold Violet
bldcya=${txtbld}$(tput setaf 6)  # Bold Cyan
bldwht=${txtbld}$(tput setaf 7)  # Bold White
blink=$(tput blink)              # Blink
bold=$(tput bold)                # Bold
reverse=$(tput smso)             # Reverse Colors
underline=$(tput smul)           # Underline

#-------------------------------------------------
#Notes
    #Add install/update dependiencies option
    #Other
    #Python: Only needed for Arch
    #Python3.3: pyvenv venv
    #Python3.0: python3.6 -m venv
    #Python2.0: virtualenv2 venv
    #Activate Python: source venv/bin/activate
    #[Neofetch] super awesome system info script
    #Install for Ubuntu: sudo apt install neofetch
    #Install for Arch: yaourt -S neofetch
    #gnome-terminal -e "watch -n1 -d ccache -s"
    #tilix -q -e "watch -n1 -d ccache -s"
    #tilix -q -e "climate overview"
    #sudo pacman -Sy python2-virtualenv
    #virtualenv2 venv
    #export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx14g"
    #./prebuilts/sdk/tools/jack-admin kill-server
    #./prebuilts/sdk/tools/jack-admin start-server
    #export LC_ALL=C
    #breakfast dumpling 
    #make -j14
    #or brunch dumpling
    #
    #DHO's cleaning rules
    #Change-Id: I0a266580874d45bab011b2dc59387603d83cf917
    #https://github.com/Flash-ROM/build/commit/c7efc9adb6612c8d4626b69a55983b4efdb78bbb
    #
#---------------------------------------------------

pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}

pause0(){
    read -p "                        Press [Enter] key to continue..." fackEnterKey
}

# function to display menus
function show_menus() {
    clear
    echo ""
    tput setaf 1
    #echo "Lets Get ROM'd Up!" && sleep 2
    echo "   OnePlus 5T  " && sleep 2
    tput setaf 2
    clear
    echo "   ROM Builder  "
    echo " [KillerDroid96]"
    echo ""
    echo "================="
    echo "|   Main Menu   |"
    echo "================="
    echo "| [1] Setup     |"
    echo "| [2] Build     |"
    echo "| [e] Exit      |"
    echo "================="
    echo ""
}
read_options(){
    local choice
    read -p "Enter choice:" choice
    case $choice in
        1) Setup ;;
        2) Build ;;
        e) exit 0;; 
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Build(){
    show_menus(){
    clear
    echo "============="
    echo "|   Build   |"
    echo "============="
    echo "| [1] Clean |"
    echo "| [2] Dirty |"
    echo "| [e] Exit  |"
    echo "============="
}
read_options(){
    local choice
    tput setaf 7; read -p "Enter choice [ 1 - 3] " choice
    case $choice in
        1) Clean ;;
        2) Dirty ;;
        e) exit 0 ;;
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Clean(){
        clear
        tput setaf 2; echo "Getting Things Ready"
        tput setaf 7;
        virtualenv2 venv
        source venv/bin/activate
        tput setaf 1; echo "Removing Entire Build Directory!" && sleep 3
        tput setaf 7;
        make clobber
        make clean
        tput setaf 2; echo "Syncing Repo!" && sleep 2
        #time repo sync --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune
        repo sync --force-sync -j$( nproc --all )
        tput setaf 1; echo "Building ROM!" && sleep 3
        tput setaf 2
        export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx14g"
        ./prebuilts/sdk/tools/jack-admin kill-server
        ./prebuilts/sdk/tools/jack-admin start-server
        . build/envsetup.sh 
        lunch du_dumpling-userdebug
        #time mka bacon -j10
        time make bacon -j$( nproc --all )
        pause
        return
}
Dirty(){
        clear
        tput setaf 2; echo "Building Dirty OnePlus 5T ROM"
        tput setaf 7;
        virtualenv2 venv
        source venv/bin/activate
        echo ${red}"Surgical Strike Starting"${normal}
        make burst
        time repo sync --force-broken --force-sync --no-clone
        export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx14g"
        ./prebuilts/sdk/tools/jack-admin kill-server
        ./prebuilts/sdk/tools/jack-admin start-server
        . build/envsetup.sh
        tput setaf 1; echo "Building ROM!" && sleep 3 
        tput setaf 2
        lunch du_dumpling-userdebug
        time mka bacon -j16
        pause
        return
}
}
Setup(){
    show_menus() {
    clear
    tput setaf 2
    echo "============================"    
    echo "|          Setup           |"
    echo "============================"
    echo "| [1] Install Dependencies |"
    echo "| [2] Setup Google Source  |"
    echo "| [3] Create ROM Directory |" 
    echo "| [4] Initialize Repo      |"
    echo "| [5] Setup CCache         |"
    echo "| [e] Exit                 |"
    echo "============================"
}
read_options(){
    local choice
    tput setaf 7; read -p "Enter choice [ 1 - 6] " choice
    case $choice in
        1) Install_Dependencies ;;
        2) Setup_Google_Source ;;
        3) Create_ROM_Directory ;;
        4) Initialize_Repo ;;
        5) Setup_CCache ;;
        e) exit 0;;
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Install_Dependencies(){
    show_menus(){
    clear
    tput setaf 2
    echo "=================="
    echo "|  Dependencies  |"
    echo "=================="
    echo "| [1] Arch       |"
    echo "| [2] Ubuntu     |"
    echo "| [3] Exit       |" 
    echo "=================="
}
read_options(){
    local choice
    tput setaf 7; read -p "Enter choice [ 1 - 3] " choice
    case $choice in
        1) Arch ;;
        2) Ubuntu ;;
        e) exit 0;;
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Arch(){
        tput setaf 1; echo "Installing Dependencies for Arch"
        tput setaf 3; echo "Gettings Things Ready"
        tput setaf 2; sudo pacman -Syu
        tput setaf 3; echo "Installing Android Dependencies" && sleep 3
        tput setaf 2; sudo pacman -S  git gnupg flex bison gperf sdl wxgtk2 bash-completion \
        squashfs-tools curl ncurses zlib schedtool perl-switch zip \
        unzip libxslt python2-virtualenv bc rsync  \
        xml2 lzop pngcrush imagemagick jdk8-openjdk  jdk9-openjdk repo android-tools python-networkx 
        tput setaf 3; echo "Installing 64 bit Dependencies" && sleep 3
        tput setaf 2; sudo pacman -S ncurses5-compat-libs lib32-ncurses5-compat-libs lib32-zlib lib32-ncurses lib32-readline
        tput setaf 3; echo "Installing Extra Dependencies" && sleep 3
        tput setaf 2; sudo pacman -S ca-certificates-mozilla fakeroot make pkg-config maven tmux screen w3m ncftp yaourt
        tput setaf 2; yaourt -S neofetch aur/tilix 
        tput setaf 3; echo "Check & Reinstall Dependencies " && sleep 3
        tput setaf 2; sudo pacman -S base-devel
        tput setaf 3; echo "Disable PGP checking from AUR" && sleep 3
        export MAKEPKG="makepkg --skippgpcheck"
        tput setaf 2;
        pacaur -S libtinfo --noconfirm
        pacaur -S lib32-ncurses5-compat-libs --noconfirm
        pacaur -S ncurses5-compat-libs --noconfirm
        pause
        return
}
Ubuntu(){
         echo "Installing Dependencies for Ubuntu"
         sudo apt install neofetch tilix
         pause
         return
}
}
Setup_Google_Source(){
    echo "Setting up Google Source"
    mkdir ~/bin
    PATH=~/bin:$PATH
    curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
    pause
    return
}
Create_ROM_Directory(){
    echo "Creating ROM Directory:"
    echo "mkdir ~/ROM-Directory"
    pause
    mkdir ~/ROM-Directory
    pause
    return
}
Initialize_Repo(){
    echo "Initialize Repo:"
    echo "cd ~/ROM-Directory"
    pause
    cd ~/ROM-Directory
    echo "Example: repo init -u https://github.com/username/platform_manifest.git -b branch"
    pause
    echo "Initializing DirtyUnicorns"
    pause
    repo init -u https://github.com/DirtyUnicorns/android_manifest -b o8x-caf
    return
}
Setup_CCache(){
    echo "export USE_CCACHE=1" >> ~/.bashrc
    echo "~/ROM-Directory/prebuilts/misc/linux-x86/ccache/ccache -M 60G"
    pause
    return
}
}

while true
do
    show_menus
    read_options 
done