#!/bin/bash
########################
#        CREDITS       #
########################
# -KillerDroid96
########################
source $HOME/Github/Scripts/linux/Shell/shell_aliases
source $HOME/Github/Scripts/linux/Shell/shell_ask
source $HOME/Github/Scripts/linux/Shell/shell_banner
source $HOME/Github/Scripts/linux/Shell/shell_colors
source $HOME/Github/Scripts/linux/Shell/shell_exports
source $HOME/Github/Scripts/linux/Shell/shell_functions
source $HOME/Github/Scripts/linux/Shell/shell_list
source $HOME/Github/Scripts/linux/Shell/shell_motd
source $HOME/Github/Scripts/linux/Shell/shell_paths
source $HOME/Github/Scripts/linux/Shell/shell_prompts
source $HOME/Github/Scripts/linux/Shell/shell_sources