#!/bin/bash
########################
#        CREDITS       #
########################
# -KillerDroid96
########################

$HOME/Github/Scripts/linux/Shell/shell_aliases
$HOME/Github/Scripts/linux/Shell/shell_ask
$HOME/Github/Scripts/linux/Shell/shell_banner
$HOME/Github/Scripts/linux/Shell/shell_colors
$HOME/Github/Scripts/linux/Shell/shell_exports
$HOME/Github/Scripts/linux/Shell/shell_functions
$HOME/Github/Scripts/linux/Shell/shell_list
$HOME/Github/Scripts/linux/Shell/shell_motd
$HOME/Github/Scripts/linux/Shell/shell_paths
$HOME/Github/Scripts/linux/Shell/shell_prompts
$HOME/Github/Scripts/linux/Shell/shell_sources
