#!/bin/bash

if [ -f $HOME/Github/Scripts/Linux/Bash/.bash_functions ]; then
   source $HOME/Github/Scripts/Linux/Bash/.bash_functions
fi

# This is a general-purpose function to ask Yes/No questions in Bash, either
# with or without a default answer. It keeps repeating the question until it
# gets a valid answer.
ask() {
    # https://djm.me/ask
    local prompt default reply
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi
        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "
        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read reply </dev/tty
        # Default?
        if [ -z "$reply" ]; then
            reply=$default
        fi
        # Check if the reply is valid
        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

update_system() {
clear
tput setaf 29
if ask "Update System?"; then
    echo "Yes"
    tput setaf 5; echo "Updating System"
    sudo pacman -Syyu --quiet --noconfirm
    tput setaf 2; echo "Installing AUR Package Manager" 
    cd && git clone https://aur.archlinux.org/trizen-git.git 
    cd trizen-git && makepkg -si && cd
    sudo rm -r trizen-git
    clear
    tput setaf 2
    echo ""
    echo "System Update Complete"
    echo "" 
else
    echo "No"
fi
}

setup_gitconfig () {
tput setaf 30
if ask "Setup Github Login?"; then
    sudo pacman -Syyu git xclip
    ssh-keygen -t rsa -b 4096 -C "mkeller96@gmail.com"
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa
    xclip -sel clip < ~/.ssh/id_rsa.pub
    echo "Login to Github & Add SSH Key"
    git config --global user.name "KillerDroid96"
    git config --global user.email "mkeller96@gmail.com"
    git config --global credential.helper "cache --timeout=7200"
    tput setaf 2
    echo ""
    echo "Github Setup Complete"
    echo "" 
else
    echo "No"
fi
}

install_packages() {
tput setaf 31
if ask "Install My Additional Packages?"; then
    tput setaf 31; echo "Installing Addition Packages"
    trizen -S --needed --quiet --noedit --noconfirm acpi apg alsi baobab bc bcompare cava chromium clex climate cmatrix cylon elinks figlet glances hollywood htop jp2a neofetch qdirstat-git rar rig screenfetch spotify telegram-desktop w3m yakuake
    echo "===================================================="
    echo "|                     Programs                     |"
    echo "===================================================="
    echo "| acpi            # Displays Battery Percent       |"
    echo "| apg             # Generates Random Password      |"
    echo "| alsi            # System Info Like Neofetch      |"
    echo "| baobab          # Storage Analyzer               |"
    echo "| bcompare        # Compares Files & Folders       |"
    echo "| cava            # Console Audio Visualizer       |"
    echo "| chromium        # Web Browser                    |"
    echo "| clex            # Console File Manager           |"
    echo "| climate         # Command Line Tools             |"
    echo "| cmatrix         # Displays Matrix Effect         |"
    echo "| cylon           # Arch Maintenance Program       |"
    echo "| elinks          # Console Web Browser            |"
    echo "| figlet          # Outputs Text in ASCII Art      |"
    echo "| glances         # System Overview                |"
    echo "| hollywood       # Hacker Movie Scene             |"
    echo "| htop            # System Status Overview         |"
    echo "| jp2a            # Converts JPG to ASCII Art      |"
    echo "| neofetch        # System Information Overview    |"
    echo "| qdirstat-git    # Sorts Files by Size            |"
    echo "| rig             # Random ID Generator            |"
    echo "| yakuake         # Drop Down Terminal             |"
    echo "===================================================="   
    figlet KillerDroid96
    tput setaf 2
    echo ""
    echo "Additional Packages Install Complete"
    echo "" 
else
    echo "No"
fi
}

install_android() {
tput setaf 32
if ask "Install Android Build Dependencies?"; then
    echo "Installing Android Dependencies" && sleep 3
    trizen -S make fakeroot --noconfirm
    trizen -Syyu --needed --quiet --noedit --noconfirm aosp-devel base-devel lineageos-devel
    echo "Disable PGP checking from AUR" && sleep 3
    export MAKEPKG="makepkg --skippgpcheck"
    tput setaf 2;
    trizen -S --needed --quiet libtinfo --skipinteg --noconfirm 
    trizen -S --needed --quiet lib32-ncurses5-compat-libs --skipinteg --noconfirm 
    trizen -S --needed --quiet ncurses5-compat-libs --skipinteg --noconfirm
    tput setaf 2
    echo ""
    echo "Android Setup Complete"
    echo "" 
else
    echo "No"
fi
}

setup_du() {
tput setaf 33
if ask "Setup Build for Dirty Unicorns?"; then
    mkdir ~/Github/DU
    cd ~/Github/DU
    virtualenv2 venv
    source venv/bin/activate
    repo init -u http://github.com/DirtyUnicorns/android_manifest.git -b o8x-caf
    mkdir ~/Github/DU/.repo/local_manifests
    cp ~/Github/Scripts/Linux/Files/du_manifest.xml ~/Github/DU/local_manifests/du_manifest.xml
    repo sync --force-sync -j$( nproc --all )
    ccache -M 50G
    echo "Enter du_rom in a Terminal to Start Build"
else
    echo "No"
fi
}

add_bashrc() {
tput setaf 34
if ask "Add .bashrc Changes?"; then
    echo "Yes"
    cp -b $HOME/Github/Scripts/Linux/Bash/.bashrc $HOME && source ~/.bashrc
    tput setaf 2
    echo ""
    echo ".bashrc Changes Complete"
    echo "" 
else
    echo "No"
fi
}

add_sshd() {
tput setaf 35
# Default to Yes if the user presses enter without giving an answer:
if ask "Add sshd_config Changes?" Y; then
    echo "Yes"
    sudo cp ~/Github/Scripts/Linux/Files/sshd_config /etc/ssh/sshd_config
    tput setaf 2
    echo ""
    echo "SSHD Configuration Complete"
    echo "" 
else
    echo "No"
fi
}

add_neofetch() {
tput setaf 36
if ask "Add Neofetch Config?" Y; then
    echo "Yes"
    cp Github/Scripts/Files/neofetch ~/.config/neofetch/config
    tput setaf 2
    echo ""
    echo "Neofech Changes Complete"
    echo "" 
else
    echo "No"
fi
}

pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}

what_dm() {
tput setaf 37
if ask "Show Display Manager?" Y; then
    echo "Yes"
file /etc/systemd/system/display-manager.service &> $HOME/Github/arch_setup.log 
ps auxf | awk '{print$11}' | \grep -e "^/.*dm$" -e "/.*slim$" # Prints Display Manager
echo -n "What Is your Display Manager?"
read display
case $display in
GDM|gdm|gdm.service)
echo "Disabling GDM"
sudo systemctl disable gdm.service
;;
LightDM|lightdm|lightdm.service)
echo "Disabling LightDM"
sudo systemctl disable lightdm.service
;;
LXDM)
echo "Disabling LXDM"
sudo systemctl disable lxdm.service
;;
SDDM|sddm)
echo "Disabling SDDM"
sudo systemctl disable sddm.service
;;
XDM)
echo "Disabling XDM"
sudo systemctl disable xdm.service
;;
*)
echo don\'t know
;;
esac
else
    echo "No"
fi
}

# function to display menus
show_menus() {
tput setaf 38
if ask "Install Desktop Environments?" Y; then
    echo "Yes"
    clear
    echo ""
    echo "Desktop Environments"
    echo "  [KillerDroid96]"
    echo ""
    echo "===================="
    echo "|     Main Menu    |"
    echo "===================="
    echo "|  [1] KDE         |"
    echo "|  [2] Gnome       |"
    echo "|  [3] Pantheon    |"
    echo "|  [4] Xfce        |"
    echo "|  [h] Help        |"
    echo "|  [e] Exit        |"
    echo "===================="
read desktop
case $desktop in
KDE|1)
    if ask "Install KDE Plasma Desktop Environment?" N; then
        trizen -Syu --needed --quiet --noedit --noconfirm plasma plasma-desktop kde-appllications powerdevil
        sudo systemctl enable sddm.service
    else
        echo "No"
    fi
;;
Gnome|gnome|2)
    if ask "Install Gnome Desktop Environment?" N; then
        trizen -Syu --needed --quiet --noedit --noconfirm gnome gnome-extra gnome-tweak-tool
        sudo systemctl enable gdm.service
    else
        echo "No"
    fi
;;
Pantheon|pantheon|3)
    if ask "Install Patheon Desktop Environment?" N; then
        echo "Still working on this one" #trizen -S --quiet --noconfirm 
        trizen -Syu --needed --quiet --noedit --noconfirm lightdm-devel
        sudo systemctl enable lightdm-pantheon-greeter.service
    else
        echo "No"
    fi
;;
Xfce|xfce|4)
    if ask "Install Xfce Desktop Environment?" N; then
        trizen -Syu --needed --quiet --noedit --noconfirm xfwm4 xorg-xinit xfce4 xfce4-goodies mousepad menulibre xfce4-pulseaudio-plugin lightdm-devel
        xinit xfwm4
        xinit xfce4
        sudo systemctl enable xfwm4.service
        sudo systemctl enable lightdm.service
        pause   
    else
        echo "No"
    fi
;;
Help|help|h)
    clear
    echo ""
    echo "Install Desktop Environment by entering the number, letter or name"
    echo ""
    pause
    clear
    show_menus
;;
Exit|e|exit)
    clear
    exit 0
;;
*)
echo don\'t know
;;
esac
else
    echo "No"
fi
}

while true
do
    update_system
    setup_gitconfig
    install_packages
    install_android
    setup_du
    add_bashrc
    add_sshd
    add_neofetch
    what_dm
    show_menus
    read_desktop 
done
    