#!/bin/bash
#
# Copyright (C) 2017-2018 Matthew Keller
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
pause(){
  tput setaf 2; read -p "Press [Enter] key to continue..." fackEnterKey
}

pause0(){
    read -p "                        Press [Enter] key to continue..." fackEnterKey
}
		tput setaf 1; echo "Add My Changes?"
		pause
		echo ""
		echo " Adding .bashrc Changes "
		echo ""
		cp -b $HOME/Github/Scripts/Linux/.bashrc $HOME && source ~/.bashrc && touch "$HOME/.bashrc"
		echo ""
		echo " Installing Package Dependiencies "
		echo ""
 		ossetup
		echo ""
      