#!/bin/bash

ask() {
    # https://djm.me/ask
    local prompt default reply

    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "

        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read reply </dev/tty

        # Default?
        if [ -z "$reply" ]; then
            reply=$default
        fi

        # Check if the reply is valid
        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}

pause0(){
    read -p "                        Press [Enter] key to continue..." fackEnterKey
}

if ask "Do you have Trizen Installed?" N; then
    echo "Continuing"
else
    echo "Installing Trizen"
    sudo pacman -Syu --quiet --noconfirm trizen 
fi    

# function to display menus
function show_menus() {
    clear
    echo ""
    tput setaf 1
    #echo "Lets Get ROM'd Up!" && sleep 2
    tput setaf 2
    clear
    echo ""
	echo "Desktop Environments"
    echo "  [KillerDroid96]"
    echo ""
    echo "===================="
    echo "|     Main Menu    |"
    echo "===================="
    echo "|  [1] KDE         |"
    echo "|  [2] Gnome       |"
    echo "|  [3] Pantheon    |"
    echo "|  [4] Xfce        |"
    echo "|  [e] Exit        |"
    echo "===================="
    echo ""
}
read_options(){
    local choice
    read -p "Enter choice:" choice
    case $choice in
        1) KDE ;;
        2) Gnome ;;
		3) Pantheon ;;
		4) Xfce ;;
        e) exit 0;; 
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}

KDE(){
	if ask "Install KDE Plasma Desktop Environment?" N; then
		pacman -S --quiet --noconfirm
	else
		echo "No"
	fi
}

Gnome(){
	if ask "Install Gnome Desktop Environment?" N; then
		pacman -S --quiet --noconfirm
	else
		echo "No"
	fi
}

Pantheon(){
	if ask "Install Patheon Desktop Environment?" N; then
		pacman -S --quiet --noconfirm
	else
		echo "No"
	fi
}

Xfce(){
	if ask "Install Xfce Desktop Environment?" N; then
		pacman -S --quiet --noconfirm
	else
		echo "No"
	fi
}

while true
do
    show_menus
    read_options 
done