#!/bin/bash
########################
#        CREDITS       #
########################
# -KillerDroid96
########################
if [ -f $HOME/Github/Scripts/Linux/Shell/shell_alias ]; then
    source $HOME/Github/Scripts/Linux/Shell/shell_alias
fi

if [ -f $HOME/Github/Scripts/Linux/Shell/shell_color ]; then
	source $HOME/Github/Scripts/Linux/Shell/shell_color
fi

if [ -f $HOME/Github/Scripts/Linux/Shell/shell_function ]; then	
	source $HOME/Github/Scripts/Linux/Shell/shell_function
fi

if [ -f $HOME/Github/Scripts/Linux/Shell/shell_path ]; then	
	source $HOME/Github/Scripts/Linux/Shell/shell_path
fi

if [ -f $HOME/Github/Scripts/Linux/Shell/shell_prompt ]; then	
	source $HOME/Github/Scripts/Linux/Shell/shell_prompt
fi

if [ -f $HOME/nathan_scripts/common ]; then
	source $HOME/nathan_scripts/common
fi

if [ -f /etc/.bash_completion ]; then
	source /etc/.bash_completion
fi

if [ -f /etc/.bash_profile ]
    source /etc/.bash_profile
fi

if -f [ /.git-prompt.sh ]; then
    source ~/.git-prompt.sh
fi