#!/bin/bash
########################
#        CREDITS       #
########################
# -KillerDroid96
# -Akhilnarang
# -Nathanchance
########################
source $HOME/Github/Scripts/Linux/Shells/shell_colors
#############
# FUNCTIONS #
#############

### ZSH ###
function lists() {
    functions
    local
    alias
}

confirm() {
    local answer
    echo -ne "zsh: sure you want to run '${YELLOW}$*${NC}' [yN]? "
    read -q answer
        echo
    if [[ "${answer}" =~ ^[Yy]$ ]]; then
        command "${@}"
    else
        return 1
    fi
}

confirm_wrapper() {
    if [ "$1" = '--root' ]; then
        local as_root='true'
        shift
    fi

    local prefix=''

    if [ "${as_root}" = 'true' ] && [ "${USER}" != 'root' ]; then
        prefix="sudo"
    fi
    confirm ${prefix} "$@"
}

poweroff() { confirm_wrapper --root $0 "$@"; }
reboot() { confirm_wrapper --root $0 "$@"; }
hibernate() { confirm_wrapper --root $0 "$@"; }

ask() {
    # https://djm.me/ask
    local prompt default reply
    while true; do
        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi
        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "
        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read reply </dev/tty
        # Default?
        if [ -z "$reply" ]; then
            reply=$default
        fi
        # Check if the reply is valid
        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

ask_y(){
if ask "Do you want to Continue?" Y; then
    echo "${green}Continuing${normal}"
else
    echo "${red}Stopping${normal}"
    return
fi
}

ask_n(){
    if ask "Do you want to Continue?" N; then
    echo "${green}Continuing${normal}"
else
    echo "${red}Stopping${normal}"
    return
fi
}

### BASH ###

# Will create [file].bak in the same directory
function backup() { 
    cp "$1"{,.bak};
} 

function calc() { # terminal calculator
    echo "scale=3;$@" | bc -l
}

function cl() { # cd and ls in one
    local dir="$1"
    local dir="${dir:=$HOME}"
    if [[ -d "$dir" ]]; then
        cd "$dir" >/dev/null; ls
    else
        echo "bash: cl: $dir: Directory not found"
    fi
}

function clv() { # cd and ls in one
    local dir="$1"
    local dir="${dir:=$HOME}"
    if [[ -d "$dir" ]]; then
        cd "$dir" >/dev/null; ll
    else
        echo "bash: cl: $dir: Directory not found"
    fi
}

# Prints weather information 
function forcast(){
    printf "\n    Todays Forcast : $(curl -s wttr.in/~Pittsburg,KS?0?q?T | awk '/°(C|F)/ {printf $(NF-1) $(NF) " ("a")"} /,/ {a=$0}') \n ${Color_Off}" 
    printf "                     : $(curl -s wttr.in/~Overland+Park,KS?0?q?T | awk '/°(C|F)/ {printf $(NF-1) $(NF) " ("a")"} /,/ {a=$0}') \n\n ${Color_Off}"
}

function ipif() { # lists ip, hostname, city, region, country, loc, org, postal
    if grep -P "(([1-9]\d{0,2})\.){3}(?2)" <<< "$1"; then
    curl ipinfo.io/"$1"
    else
    ipawk=($(host "$1" | awk '/address/ { print $NF }'))
    curl ipinfo.io/${ipawk[1]}
    fi
    echo
}

# Usage mcd test, creates and moves into test directory
function mcd () { 
    mkdir -p $1
    cd $1
}
# Usage todo -l -c -r
function todo() {
    if [[ ! -f $HOME/.todo ]]; then
        touch "$HOME/.todo"
    fi

    if ! (($#)); then
        cat "$HOME/.todo"
    elif [[ "$1" == "-l" ]]; then
        nl -b a "$HOME/.todo"
    elif [[ "$1" == "-c" ]]; then
        > $HOME/.todo
    elif [[ "$1" == "-r" ]]; then
        nl -b a "$HOME/.todo"
        eval printf %.0s- '{1..'"${COLUMNS:-$(tput cols)}"\}; echo
        read -p "Type a number to remove: " number
        sed -i ${number}d $HOME/.todo "$HOME/.todo"
    else
        printf "%s\n" "$*" >> "$HOME/.todo"
    fi
}

function todos () { # Displays items in .note
    echo ""
    echo "==========================="
    echo "|          To Do          |"
    echo "==========================="
    cat $HOME/.todo
    echo "==========================="
    echo ""
}

function todoedit () {
    nano $HOME/.todo
}

function note () { #Usage note test, saves to .notes
        # if file doesn't exist, create it
    if [[ ! -f $HOME/.notes ]]; then
        touch "$HOME/.notes"
    fi

    if ! (($#)); then
        # no arguments, print file
        cat "$HOME/.notes"
    elif [[ "$1" == "-c" ]]; then
        # clear file
        printf "%s" > "$HOME/.notes"
    else
        # add all arguments to file
        printf "%s\n" "| $*" >> "$HOME/.notes"
    fi
}

function notes () { # Displays items in .note
    echo ""
    echo "==========================="
    echo "|          Notes          |"
    echo "==========================="
    cat $HOME/.notes
    echo "==========================="
    echo ""
}

function notesedit () {
    nano $HOME/.notes
}

function numfiles() { # Usage numfiles scripts > 88 files in scripts
    # numfiles test > 10 files in test
    N="$(ls $1 | wc -l)"; 
    echo "$N files in $1";
}

function pps() { # Search for a process containing a given name
ps aux | grep "$@" | grep -v 'grep';
}

function rehistory(){ # history displays comand history, use !208 etc to repeat command
    history | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl |  head -n10
}

function sbs() { # Lists files by size in current directory
    du -b --max-depth 1 | sort -nr | perl -pe 's{([0-9]+)}{sprintf "%.1f%s", $1>=2**30? ($1/2**30, "G"): $1>=2**20? ($1/2**20, "M"): $1>=2**10? ($1/2**10, "K"): ($1, "")}e';
} 

function shopts() {         # Sets Shell Options
    shopt -s cdspell        # This will correct minor spelling errors in a cd command.
    shopt -s histappend     # Append to history rather than overwrite
    shopt -s checkwinsize   # Check window after each command
    shopt -s dotglob        # files beginning with . to be returned in the results of path-name expansion.
    shopt -s no_empty_cmd_completion # Disable completion when the input buffer is empty
    shopt -s 
}

function wheres (){ # Usage whereis scripts, displays all locations with the word scripts (case sensitive)
  find . -name "$1*";
}

function upinfo() {
    echo -ne "${green}$(hostname) ${red}uptime is ${cyan} \\t ";uptime | awk /'up/ {print $3,$4,$5,$6,$7,$8,$9,$10,$11}';
}

function git_config() {
    git config --global user.email "mkeller96@gmail.com"
    git config --global user.name "KillerDroid96"
    git config --global credential.helper "cache --timeout=7200"
    git config -l
}

function mosh1() {
    sudo systemctl enable sshd.service;
    sudo systemctl start sshd.service;
    echo -e "Mosh Server Started";
}

# Neofetch alias
function nf() {
    echo
    neofetch \
        --kernel_shorthand on \
        --distro_shorthand tiny \
        --os_arch off \
        --uptime_shorthand tiny \
        --speed_shorthand on \
        --install_time off \
        --color_blocks off
    echo
    echo
}

function trizens(){
    header "Updating System"
    trizen -Syyu --quiet --noconfirm --noedit --needed
    clear
    header "System Update Complete"
}

function trim_vbox(){
    header "Filling Empty Space"
    # No output is displayed
    sudo dd if=/dev/zero of=/var/tmp/bigemptyfile bs=4096k
    header "Deleting Empty Space"
    sudo rm /var/tmp/bigemptyfile
    header "Ready to Compact VDI"
}
##################################################################################################
##################################################################################################
##################################################################################################
##################################################################################################
##################################################################################################
# Copyright (C) 2018-2020 KillerDroid96
# Copyright (C) 2016-2018 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

function venv() {
    virtualenv2 /tmp/venv;
    source /tmp/venv/bin/activate;
}

function venv_stop(){
    deactivate
    rm -rf "${HOME}/venv"
}

function sync_repo() {
    header "SYNCING LATEST SOURCES"; echo
    repo sync -j$( nproc --all ) --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune
}

function gdrive_rom() {
    #gdrive about -c /home/matt/.gdrive
    #gdrive -c /home/matt/.gdrive sync upload $HOME/Github/Uploads 1znWrZTRSwAvWgVNHz4hsvEEgaOcrpS8z &> out.log 
    gdrive about -c /home/matt/.gdrive-secondary #&> out.log  
    gdrive -c /home/matt/.gdrive-secondary sync upload $HOME/Github/Uploads 1lOVVWYg_itAPwaUWbMhkvF2P51wzr46v #&> out.log  
    echo "https://drive.google.com/drive/folders/1lOVVWYg_itAPwaUWbMhkvF2P51wzr46v"
}

###############
#             #
#  VARIABLES  #
#             #
###############

SOURCE_FOLDER=${ROM_FOLDER}/${ROM}

# What OS are we on?
OS=$(UNAME=$(uname); echo "${UNAME,,}")
# GNU readlink is needed for SCRIPTS_FOLDER
[[ ${OS} = "darwin" ]] && alias readlink=greadlink

# Location of "scripts" folder
SCRIPTS_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
BIN_FOLDER=${SCRIPTS_FOLDER}/bin

# Common locations amongst scripts
#KERNEL_FOLDER=${HOME}/kernels
#MISC_FOLDER=${HOME}/misc
#REPO_FOLDER=${HOME}/repos
#ROM_FOLDER=${HOME}/roms
#TC_FOLDER=${HOME}/toolchains
#WEB_FOLDER=${HOME}/web



# Number of make threads
if [[ ${OS} = "darwin" ]]; then
    THREADS=$(sysctl hw.ncpu | cut -d " " -f 2)
else
    THREADS=$(nproc --all)
fi
    JOBS_FLAG="-j${THREADS}"

###############
#             #
#  FUNCTIONS  #
#             #
###############

# Alias for echo to print escape codes
function echo() {
    command echo -e "$@"
}

# Prints a formatted header to point out what is being done to the user
function header() {
    if [[ -n ${2} ]]; then
        COLOR=${2}
    else
        COLOR=${RED}
    fi
    echo "${COLOR}"
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "|   ${1}   |"
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "${RST}"
}

# Formats the time
function format_time() {
    MINS=$(((${2} - ${1}) / 60))
    SECS=$(((${2} - ${1}) % 60))
    if [[ ${MINS} -ge 60 ]]; then
        HOURS=$((MINS / 60))
        MINS=$((MINS % 60))
    fi

    if [[ ${HOURS} -eq 1 ]]; then
        TIME_STRING+="1 HR, "
    elif [[ ${HOURS} -ge 2 ]]; then
        TIME_STRING+="${HOURS} HRS, "
    fi

    if [[ ${MINS} -eq 1 ]]; then
        TIME_STRING+="1 MIN"
    else
        TIME_STRING+="${MINS} MINS"
    fi

    if [[ ${SECS} -eq 1 && -n ${HOURS} ]]; then
        TIME_STRING+=", AND 1 SEC"
    elif [[ ${SECS} -eq 1 && -z ${HOURS} ]]; then
        TIME_STRING+=" AND 1 SEC"
    elif [[ ${SECS} -ne 1 && -n ${HOURS} ]]; then
        TIME_STRING+=", AND ${SECS} SECS"
    elif [[ ${SECS} -ne 1 && -z ${HOURS} ]]; then
        TIME_STRING+=" AND ${SECS} SECS"
    fi

    echo "${TIME_STRING}"
}

# Prints an error in bold red
function display_error() {
    echo
    echo "${RED}${1}${RST}"
    [[ -z ${2} ]] && echo
}

# Prints an error in bold red and exits the script
function die() {
    if [[ ${TG} ]]; then
        # Info must be resourced so public chats don't get notified
        load_botinfo
        {
            echo "\`\`\`"
            echo "An error was detected while running the following command:"
            echo "$(basename "${0}") ${PARAMS}"
            echo "The error was:"
            echo "$*"
            echo "\`\`\`"
        } > /tmp/death-tg-msg
        notify "$(cat /tmp/death-tg-msg)"
    fi

    display_error "$@"
    exit
}

# Prints a warning in bold yellow
function warn() {
    echo
    echo "${YLW}${1}${RST}"
    [[ -z ${2} ]] && echo
}

# Enforces the value needed for two-part flags
function enforce_value() {
    [[ $# -lt 1 ]] && die "A additional value is needed for one of the flags passed to this script!"
}

# Add a remote if it doesn't exist
function add_remote() {
    if ! git remote | grep -q -m 1 "${1}"; then
        git remote add "${1}" "${2}"
    fi
}

# Set up a virtual environment for Python
function mkavenv {
    virtualenv2 "${HOME}/venv"
    source "${HOME}/venv/bin/activate"
}

# Remove virtual environment
function rmvenv {
    deactivate
    rm -rf "${HOME}/venv"
}

# Source Telegram bot information
function load_botinfo() {
    [[ -f ${HOME}/.botinfo ]] && source ~/.botinfo
}

load_botinfo

# Require a parameter to opt out of macOS_check
[[ $# -lt 1 && ${OS} = "darwin" ]] && die "Wrong window! ;)"

# Convert a file location to web link
function web_link() {
    #gdrive -c /home/matt/.gdrive sync upload $HOME/Github/Uploads 1znWrZTRSwAvWgVNHz4hsvEEgaOcrpS8z &> out.log 
    #echo "https://goo.gl/m7ssB5"

    gdrive -c /home/matt/.gdrive-secondary sync upload $HOME/Github/Uploads 1lOVVWYg_itAPwaUWbMhkvF2P51wzr46v &> out.log
    echo "https://goo.gl/wDXHyD"
}

# Telegram notifier function
TOKEN=513663559:AAFltOrxX0FGsxW83jVMqProcRBCceeKHeM
CHAT_ID=488672694
function notify_id(){
    curl https://api.telegram.org/bot"${TOKEN}"/getUpdates
}
function notify() {
    if [[ -z ${TOKEN} ]]; then
        display_error "notify() was called but there was no token!"
        return 1
    fi

    if [[ -z ${CHAT_ID} ]]; then
        display_error "notify() was called but there was no chat ID!"
        return 1
    fi

    curl -s -X POST https://api.telegram.org/bot"${TOKEN}"/sendMessage -d chat_id="${CHAT_ID}" -d parse_mode="Markdown" -d text="$*" 1>/dev/null
}

#git pull='git pull --depth=1 -p -j$( nproc --all )'
#git push='git push-j$( nproc --all )'

# function other_repos() {
#     echo "Fetching Project KillerDroid96/flash_kernel_oneplus_msm8998" && sleep 1
#     git remote add kd git@github.com:KillerDroid96/flash_kernel_oneplus_msm8998.git  &> $HOME/Github/DU/repos.log 
#     git remote add nc git@github.com:nathanchance/op5.git  &> $HOME/Github/DU/repos.log
#     git fetch nc --tags ${JOBS_FLAG}
#     git checkout -b 8.1.0 &> $HOME/Github/DU/repos.log 
#     git checkout 8.1.0 &> $HOME/Github/DU/repos.log 
#     git pull kd 8.1.0 ${JOBS_FLAG} &> $HOME/Github/DU/repos.log 
#     git pull nc 8.1.0-unified ${JOBS_FLAG} &> $HOME/Github/DU/repos.log 
#     git push --set-upstream kd 8.1.0 &> $HOME/Github/DU/repos.log  
# }

function merge_du_repos() {
    cd $HOME/Github/DU/${REPO_PATH}
    echo "Fetching Project KillerDroid96/${REPO_NAME}" && sleep 1 
    git remote add kd git@github.com:KillerDroid96/${REPO_NAME}.git &> ${REPO_LOG}
    git remote add du git@github.com:DirtyUnicorns/${REPO_NAME}.git &> ${REPO_LOG}
    git checkout -b o8x-caf &> ${REPO_LOG}
    git checkout o8x-caf &> ${REPO_LOG}
    git pull kd o8x-caf ${JOBS_FLAG} &> ${REPO_LOG}
    git pull du o8x ${JOBS_FLAG} &> ${REPO_LOG}
    git push --set-upstream kd o8x-caf &> ${REPO_LOG}
}

function du_repos() {
    REPO_LOG=$HOME/Github/DU/repos.log 
    
    REPO_PATH=build
    REPO_NAME=android_build
    merge_du_repos

    #REPO_PATH=packages/apps/Settings
    #REPO_NAME=android_packages_apps_Settings
    #merge_du_repos

    REPO_PATH=frameworks/base
    REPO_NAME=android_frameworks_base
    merge_du_repos

    REPO_PATH=vendor/du
    REPO_NAME=android_vendor_du
    merge_du_repos

    REPO_PATH=device/oneplus/msm8998-common
    REPO_NAME=android_device_oneplus_msm8998-common
    merge_du_repos
}

function merge_repos() {
    du_repos 
    other_repos    
}

function sync_all(){
    header "SETTING UP BUILD ENVIRONMENT"
    cd $HOME/Github/DU && mkavenv
    header "SYNCING LATEST SOURCES"; echo
    repo sync -j$( nproc --all ) --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune
    header "MERGING LATEST SOURCES"; echo
    merge_repos
}

function setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'
    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi
    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail
    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
    success 'gitconfig'
  fi
}

source $HOME/Github/Scripts/Linux/Shells/shell_colors

function du_banner(){
    clear
    echo -e "============================================="
    echo -e "               ____  _      __               "
    echo -e "              / __ \(_)____/ /___  __        "
    echo -e "             / / / / / ___/ __/ / / /        "
    echo -e "            / /_/ / / /  / /_/ /_/ /         "
    echo -e "           /_____/_/_/   \__/\__, /          "
    echo -e "    __  __      _           /____/           "
    echo -e "   / / / /___  (_)________  _________  _____ "
    echo -e "  / / / / __ \/ / ___/ __ \/ ___/ __ \/ ___/ "
    echo -e " / /_/ / / / / / /__/ /_/ / /  / / / (__  )  "
    echo -e " \____/_/ /_/_/\___/\____/_/  /_/ /_/____/   "
    echo -e "                                             "
    echo -e "============================================="
    echo -e ${CL_RST}""
}

function unicorn_banner()
{
    echo -e ${RED}"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    echo -e ${RED}"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    echo -e ${RED}"%%%%%%%%%%%%%%             %%%%%%%%%%%%"
    echo -e ${RED}"%%%%%%%%%%%    %%%%%%%%%%%    %%%%%%%%%"
    echo -e ${RED}"%%%%%%%%%   %%%%%%%%%%%%%%%%%   %%%%%%%"
    echo -e ${RED}"%%%%%%%   %%%"${BLK}"&"${RED}"%%%%%%%%%%%"${BLK}"&"${RED}"%%%%%%  %%%%%"
    echo -e ${RED}"%%%%%%  %%%%%%"${BLK}"&&&"${RED}"%%%"${BLK}"&&&"${RED}"%%%"${BLK}"&&&&"${RED}"%%%   %%%"
    echo -e ${RED}"%%%%%  %%%%%%%%"${BLK}"&&&&&&&&&&"${RED}"%%%%%"${BLK}"&&&"${RED}"%%  %%"
    echo -e ${RED}"%%%%  %%%%%%%%%"${BLK}"&&&&&&&&&&&&&&"${RED}"%%%"${BLK}"&&&"${RED}"%%%%"
    echo -e ${RED}"%%%%  %%%%%%%"${BLK}"&&&"${RED}", "${BLK}"&&&&&&&&&&&&&"${RED}"%%"${BLK}"&&&&"${RED}"%%"
    echo -e ${RED}"%%%&  %%%%%"${BLK}"&&&&&&&&&&&&&&&&&&&&&"${RED}"%%%"${BLK}"&&&"${RED}"%"
    echo -e ${RED}"%%%%  %%%%"${BLK}"&&&&&&&&&&&&&&&&&&&&&&&"${RED}"%%"${BLK}"&&&"${RED}"%"
    echo -e ${RED}"%%%%  %%%"${BLK}"&&&&&&"${RED}"%%%%%%%"${BLK}"&&&&&&&&&&&&"${RED}"%"${BLK}"&&"${RED}"%%"
    echo -e ${RED}"%%%%%  %%%%"${BLK}"&&"${RED}"%%%%%%%%%"${BLK}"&&&&&&&&&&&&"${RED}"%"${BLK}"&&"${RED}"%%"
    echo -e ${RED}"%%%%%%  %%%%%%%%%%%%%%"${BLK}"&&&&&&&&&&&&&&"${RED}"%%%"
    echo -e ${RED}"%%%%%%%  %%%%%%%%%%%%"${BLK}"&&&&&&&&&&&&&&"${RED}"%%%%"
    echo -e ${RED}"%%%%%%%%   %%%%%%%%"${BLK}"&&&&&&&&&&&&&&"${RED}"%%%%%%"
    echo -e ${RED}"%%%%%%%%%%%%%%%%"${BLK}"&&&&&&&&&&&&&&&&"${RED}"%%%%%%%"
    echo -e ${RED}"%%%%%%%%%%%%%%"${BLK}"&&&&&&&&&&&&&"${RED}"%%%%%%%%%%%%"
    echo -e ${RED}"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"       
}