#!/bin/bash

#########
# PATHS #
#########
PATH=$PATH:$HOME/Github; export PATH
PATH=$PATH:$HOME/Github/Scripts; export PATH
PATH=$PATH:$HOME/Github/Scripts/Linux; export PATH
PATH=$PATH:$HOME/Github/Scripts/Linux/Files; export PATH
PATH=$PATH:$HOME/Github/Scripts/Linux/Misc; export PATH
PATH=$PATH:$HOME/Github/Scripts/Linux/ROMs; export PATH
PATH=$PATH:$HOME/Github/Scripts/Linux/Setups; export PATH
PATH=$PATH:$HOME/Github/Scripts/Linux/Shells; export PATH
PATH=$PATH:$HOME/nathan_scripts; export PATH