#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1090
#
# Helper functions
#
# Copyright (C) 2016-2018 Nathan Chancellor
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


###############
#             #
#  VARIABLES  #
#             #
###############


SOURCE_FOLDER=${ROM_FOLDER}/${ROM}

# What OS are we on?
OS=$(UNAME=$(uname); echo "${UNAME,,}")
# GNU readlink is needed for SCRIPTS_FOLDER
[[ ${OS} = "darwin" ]] && alias readlink=greadlink

# Location of "scripts" folder
SCRIPTS_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
BIN_FOLDER=${SCRIPTS_FOLDER}/bin

# Common locations amongst scripts
#KERNEL_FOLDER=${HOME}/kernels
#MISC_FOLDER=${HOME}/misc
#REPO_FOLDER=${HOME}/repos
#ROM_FOLDER=${HOME}/roms
#TC_FOLDER=${HOME}/toolchains
#WEB_FOLDER=${HOME}/web

# Colors
BLINK_RED="\033[05;31m"
BLUE="\033[01;34m"
BOLD="\033[1m"
GRN="\033[01;32m"
RED="\033[01;31m"
RST="\033[0m"
YLW="\033[01;33m"

# Number of make threads
if [[ ${OS} = "darwin" ]]; then
    THREADS=$(sysctl hw.ncpu | cut -d " " -f 2)
else
    THREADS=$(nproc --all)
fi
    JOBS_FLAG="-j${THREADS}"

###############
#             #
#  FUNCTIONS  #
#             #
###############

# Alias for echo to print escape codes
function echo() {
    command echo -e "$@"
}

# Prints a formatted header to point out what is being done to the user
function header() {
    if [[ -n ${2} ]]; then
        COLOR=${2}
    else
        COLOR=${GRN}
    fi
    echo "${COLOR}"
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "|   ${1}   |"
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "${RST}"
}

function subheader() {
    if [[ -n ${2} ]]; then
        COLOR=${2}
    else
        COLOR=${GRN}
    fi
    echo "${COLOR}"
    echo "|   ${1}   |"
    echo "${RST}"
}

function endheader() {
    if [[ -n ${2} ]]; then
        COLOR=${2}
    else
        COLOR=${GRN}
    fi
    echo "${COLOR}"
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "${RST}"
}

function tg_header() {
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
    echo "|   ${1}   |"
    echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
}

# Formats the time
function format_time() {
    MINS=$(((${2} - ${1}) / 60))
    SECS=$(((${2} - ${1}) % 60))
    if [[ ${MINS} -ge 60 ]]; then
        HOURS=$((MINS / 60))
        MINS=$((MINS % 60))
    fi

    if [[ ${HOURS} -eq 1 ]]; then
        TIME_STRING+="1 HR, "
    elif [[ ${HOURS} -ge 2 ]]; then
        TIME_STRING+="${HOURS} HRS, "
    fi

    if [[ ${MINS} -eq 1 ]]; then
        TIME_STRING+="1 MIN"
    else
        TIME_STRING+="${MINS} MINS"
    fi

    if [[ ${SECS} -eq 1 && -n ${HOURS} ]]; then
        TIME_STRING+=", AND 1 SEC"
    elif [[ ${SECS} -eq 1 && -z ${HOURS} ]]; then
        TIME_STRING+=" AND 1 SEC"
    elif [[ ${SECS} -ne 1 && -n ${HOURS} ]]; then
        TIME_STRING+=", AND ${SECS} SECS"
    elif [[ ${SECS} -ne 1 && -z ${HOURS} ]]; then
        TIME_STRING+=" AND ${SECS} SECS"
    fi

    echo "${TIME_STRING}"
}

# Prints an error in bold red
function display_error() {
    echo
    echo "${RED}${1}${RST}"
    [[ -z ${2} ]] && echo
}

# Prints an error in bold red and exits the script
function die() {
    if [[ ${TG} ]]; then
        # Info must be resourced so public chats don't get notified
        load_botinfo
        {
            echo "\`\`\`"
            echo "An error was detected while running the following command:"
            echo "$(basename "${0}") ${PARAMS}"
            echo "The error was:"
            echo "$*"
            echo "\`\`\`"
        } > /tmp/death-tg-msg
        notify "$(cat /tmp/death-tg-msg)"
    fi

    display_error "$@"
    exit
}

# Prints a warning in bold yellow
function warn() {
    echo
    echo "${YLW}${1}${RST}"
    [[ -z ${2} ]] && echo
}

# Enforces the value needed for two-part flags
function enforce_value() {
    [[ $# -lt 1 ]] && die "A additional value is needed for one of the flags passed to this script!"
}

# Add a remote if it doesn't exist
function add_remote() {
    if ! git remote | grep -q -m 1 "${1}"; then
        git remote add "${1}" "${2}"
    fi
}

# Set up a virtual environment for Python
function mkavenv {
    virtualenv2 "${HOME}/venv"
    source "${HOME}/venv/bin/activate"
}

# Remove virtual environment
function rmvenv {
    deactivate
    rm -rf "${HOME}/venv"
}

# Source Telegram bot information
function load_botinfo() {
    [[ -f ${HOME}/.botinfo ]] && source ~/.botinfo
}

load_botinfo

# Require a parameter to opt out of macOS_check
[[ $# -lt 1 && ${OS} = "darwin" ]] && die "Wrong window! ;)"

# Convert a file location to web link
function web_link() {
    #gdrive -c /home/matt/.gdrive sync upload $HOME/Github/Uploads 1znWrZTRSwAvWgVNHz4hsvEEgaOcrpS8z &> out.log 
    #echo "https://goo.gl/m7ssB5"
    gdrive -c /home/matt/.gdrive-secondary sync upload $HOME/Github/Uploads 1lOVVWYg_itAPwaUWbMhkvF2P51wzr46v &> out.log
    echo "https://goo.gl/wDXHyD"
}

# Telegram notifier function
TOKEN=513663559:AAFltOrxX0FGsxW83jVMqProcRBCceeKHeM
CHAT_ID=488672694
function notify_id(){
    curl https://api.telegram.org/bot"${TOKEN}"/getUpdates
}
function notify() {
    if [[ -z ${TOKEN} ]]; then
        display_error "notify() was called but there was no token!"
        return 1
    fi

    if [[ -z ${CHAT_ID} ]]; then
        display_error "notify() was called but there was no chat ID!"
        return 1
    fi

    curl -s -X POST https://api.telegram.org/bot"${TOKEN}"/sendMessage -d chat_id="${CHAT_ID}" -d parse_mode="Markdown" -d text="$*" 1>/dev/null
}

#git pull='git pull --depth=1 -p -j$( nproc --all )'
#git push='git push-j$( nproc --all )'

function merge_repos() {
    echo "${GRN}KillerDroid96/android_build${RST}" && sleep 1
    cd $HOME/Github/DU/build
    git remote add kd git@github.com:KillerDroid96/android_build.git &> $HOME/Github/DU/repos.log 
    git remote add du git@github.com:DirtyUnicorns/android_build.git &> $HOME/Github/DU/repos.log 
    git checkout -b o8x-caf &> $HOME/Github/DU/repos.log 
    git checkout o8x-caf &> $HOME/Github/DU/repos.log 
    git pull kd o8x-caf &> $HOME/Github/DU/repos.log 
    git pull du o8x &> $HOME/Github/DU/repos.log 
    git push --set-upstream kd o8x-caf &> $HOME/Github/DU/repos.log 

    echo "${GRN}KillerDroid96/android_frameworks_base${RST}" && sleep 1
    cd $HOME/Github/DU/frameworks/base
    git remote add kd git@github.com:KillerDroid96/android_frameworks_base.git &> $HOME/Github/DU/repos.log 
    git remote add du git@github.com:DirtyUnicorns/android_frameworks_base.git &> $HOME/Github/DU/repos.log 
    git checkout -b o8x-caf &> $HOME/Github/DU/repos.log  
    git checkout o8x-caf &> $HOME/Github/DU/repos.log  
    git pull kd o8x-caf &> $HOME/Github/DU/repos.log 
    git pull du o8x &> $HOME/Github/DU/repos.log 
    git push --set-upstream kd o8x-caf &> $HOME/Github/DU/repos.log 

    echo "${GRN}KillerDroid96/android_device_oneplus_msm8998-common${RST}" && sleep 1
    cd $HOME/Github/DU/device/oneplus/msm8998-common
    git remote add kd git@github.com:KillerDroid96/android_device_oneplus_msm8998-common.git &> $HOME/Github/DU/repos.log 
    git remote add du git@github.com:DirtyUnicorns/android_device_oneplus_msm8998-common.git &> $HOME/Github/DU/repos.log 
    git checkout -b o8x-caf &> $HOME/Github/DU/repos.log 
    git checkout o8x-caf &> $HOME/Github/DU/repos.log 
    git pull kd o8x-caf &> $HOME/Github/DU/repos.log 
    git pull du o8x-caf &> $HOME/Github/DU/repos.log 
    git push --set-upstream kd o8x-caf &> $HOME/Github/DU/repos.log 

    echo "${GRN}KillerDroid96/flash_kernel_oneplus_msm8998${RST}" && sleep 1
    cd $HOME/Github/DU/kernel/oneplus/msm8998
    git remote add kd git@github.com:KillerDroid96/flash_kernel_oneplus_msm8998.git &> $HOME/Github/DU/repos.log 
    git remote add nc git@github.com:nathanchance/op5.git &> $HOME/Github/DU/repos.log 
    git checkout -b 8.1.0 &> $HOME/Github/DU/repos.log 
    git checkout 8.1.0 &> $HOME/Github/DU/repos.log 
    git pull kd 8.1.0 &> $HOME/Github/DU/repos.log 
    git pull nc 8.1.0-unified &> $HOME/Github/DU/repos.log 
    git push --set-upstream kd 8.1.0 &> $HOME/Github/DU/repos.log 
}

function merge_repos1() {
    echo "${GRN}KillerDroid96/android_build${RST}" && sleep 1
    cd $HOME/Github/DU/build
    git remote add kd git@github.com:KillerDroid96/android_build.git  &> $HOME/Github/DU/repos.log 
    git remote add du git@github.com:DirtyUnicorns/android_build.git  &> $HOME/Github/DU/repos.log 
    git checkout -b o8x-caf &> $HOME/Github/DU/repos.log 
    git checkout o8x-caf  &> $HOME/Github/DU/repos.log 
    git pull kd o8x-caf 
    git pull du o8x 
    git push --set-upstream kd o8x-caf  &> $HOME/Github/DU/repos.log 

    echo "${GRN}KillerDroid96/android_frameworks_base${RST}" && sleep 1
    cd $HOME/Github/DU/frameworks/base
    git remote add kd git@github.com:KillerDroid96/android_frameworks_base.git  &> $HOME/Github/DU/repos.log 
    git remote add du git@github.com:DirtyUnicorns/android_frameworks_base.git  &> $HOME/Github/DU/repos.log
    git checkout -b o8x-caf &> $HOME/Github/DU/repos.log  
    git checkout o8x-caf &> $HOME/Github/DU/repos.log 
    git pull kd o8x-caf 
    git pull du o8x 
    git push --set-upstream kd o8x-caf &> $HOME/Github/DU/repos.log 

    echo "${GRN}KillerDroid96/android_device_oneplus_msm8998-common${RST}" && sleep 1
    cd $HOME/Github/DU/device/oneplus/msm8998-common
    git remote add kd git@github.com:KillerDroid96/android_device_oneplus_msm8998-common.git  &> $HOME/Github/DU/repos.log 
    git remote add du git@github.com:DirtyUnicorns/android_device_oneplus_msm8998-common.git  &> $HOME/Github/DU/repos.log 
    git checkout -b o8x-caf &> $HOME/Github/DU/repos.log 
    git checkout o8x-caf &> $HOME/Github/DU/repos.log 
    git pull kd o8x-caf 
    git pull du o8x-caf 
    git push --set-upstream kd o8x-caf &> $HOME/Github/DU/repos.log 

    echo "${GRN}KillerDroid96/flash_kernel_oneplus_msm8998${RST}" && sleep 1
    cd $HOME/Github/DU/kernel/oneplus/msm8998
    git remote add kd git@github.com:KillerDroid96/flash_kernel_oneplus_msm8998.git  &> $HOME/Github/DU/repos.log 
    git remote add nc git@github.com:nathanchance/op5.git  &> $HOME/Github/DU/repos.log 
    git checkout -b 8.1.0  &> $HOME/Github/DU/repos.log 
    git checkout 8.1.0  &> $HOME/Github/DU/repos.log 
    git pull kd 8.1.0 
    git pull nc 8.1.0-unified 
    git push --set-upstream kd 8.1.0 &> $HOME/Github/DU/repos.log 
}

function sync_all(){
    header "SETTING UP BUILD ENVIRONMENT"
    cd $HOME/Github/DU && mkavenv
    header "SYNCING LATEST SOURCES"; echo
    repo sync -j$( nproc --all ) --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune
    header "MERGING LATEST SOURCES"; echo
    merge_repos
}