#!/bin/bash
# ----------------------------------
#  variables
# ----------------------------------
EDITOR=vim
PASSWD=/etc/passwd
RED='\033[0;41;30m'
STD='\033[0;0;39m'
#---------------
# Credits
#---------------
# akhilnarang
# nathanchance
#---------------

# Build an AOSP ROM with one easy script! You will need to have the repo synced
# and configured already, use this page to help you with that:
# https://raw.githubusercontent.com/nathanchance/Android-Tools/master/Building_AOSP.txt
#
# HINT: You can add the folder this is in to your PATH variable so you can
# run it from anywhere like so:
# $ nano ~/.bashrc
# Add  export PATH=$PATH:<path_to_folder>  to the end of that file
# then hit ctrl+X, Y, then Enter
#
# example: export PATH=$PATH:/home/<username>/scripts
# example: export PATH=$PATH:/home/killerdroid96/ROMs/Developers/Matthew_Keller/Addons
# Restart your terminal

#-------------------------------------------------
#TO DO / ADD / Notes
    #Add install/update dependiencies option
    #Other
    #Python: Only needed for Arch
    #Python3.3: pyvenv venv
    #Python3.0: python3.6 -m venv
    #Python2.0: virtualenv2 venv
    #Activate Python: source venv/bin/activate
    #[Neofetch] super awesome system info script
    #Install for Ubuntu: sudo apt install neofetch
    #Install for Arch: yaourt -S neofetch
     #gnome-terminal -e "watch -n1 -d ccache -s"
        #tilix -q -e "watch -n1 -d ccache -s"
        #tilix -q -e "climate overview"
        #sudo pacman -Sy python2-virtualenv
        #virtualenv2 venv
#---------------------------------------------------

# ----------------------------------
# User defined function
# ----------------------------------

pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}

pause0(){
    read -p "                        Press [Enter] key to continue..." fackEnterKey
}

# function to display menus

function show_menus() {
    clear
    echo ""
    tput setaf 1
    echo "Lets Get ROM'd Up!" && sleep 2
    tput setaf 2
    clear
    echo ""
    echo "   ROM Builder  "
    echo " [KillerDroid96]"
    echo ""
    echo "================="
    echo "|   Main Menu   |"
    echo "================="
    echo "| [1] Setup     |"
    echo "| [2] Build     |"
    echo "| [3] SSH       |"
    echo "| [e] Exit      |"
    echo "================="
    echo ""
}
read_options(){
    local choice
    read -p "Enter choice:" choice
    case $choice in
        1) Setup ;;
        2) Build ;;
        3) SSH ;;
        e) exit 0;; 
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Build(){
    show_menus(){
    clear
    echo "============="
    echo "|   Build   |"
    echo "============="
    echo "| [1] Clean |"
    echo "| [2] Dirty |"
    echo "| [e] Exit  |"
    echo "============="
}
read_options(){
    local choice
    tput setaf 7; read -p "Enter choice [ 1 - 3] " choice
    case $choice in
        1) Clean ;;
        2) Dirty ;;
        e) exit 0 ;;
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Clean(){
        clear
        tput setaf 2; echo "Getting Things Ready"
        tput setaf 7;
        virtualenv2 venv
        source venv/bin/activate
        tput setaf 1; echo "Removing Entire Build Directory!" && sleep 3
        tput setaf 7;
        make clobber
        make clean
        tput setaf 2; echo "Syncing Repo!" && sleep 2
        time repo sync --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune
        tput setaf 1; echo "Building ROM for Nexus6P!" && sleep 3
        tput setaf 2
        . build/envsetup.sh 
        brunch dumpling -j14
        pause
        return
}
Dirty(){
        clear
        tput setaf 2; echo "Building Dirty OnePlus 5T ROM"
        tput setaf 7;
        source venv/bin/activate
        export LC_ALL=C
        make dirty
        time repo sync --force-broken --force-sync --no-clone
        . build/envsetup.sh
        tput setaf 1; echo "Building ROM!" && sleep 3 
        tput setaf 2
        brunch dumpling
        pause
        return
}
}

SSH(){
    tput setaf 2
    echo "=================="
    echo "|  Starting SSH  |"
    echo "=================="
    sudo systemctl start sshd.service 
    sudo systemctl status sshd.service
}

Setup(){
    show_menus() {
    clear
    tput setaf 2
    echo "============================"    
    echo "|          Setup           |"
    echo "============================"
    echo "| [1] Install Dependencies |"
    echo "| [2] Setup Google Source  |"
    echo "| [3] Create ROM Directory |" 
    echo "| [4] Initialize Repo      |"
    echo "| [5] Setup CCache         |"
    echo "| [e] Exit                 |"
    echo "============================"
}
read_options(){
    local choice
    tput setaf 7; read -p "Enter choice [ 1 - 6] " choice
    case $choice in
        1) Install_Dependencies ;;
        2) Setup_Google_Source ;;
        3) Create_ROM_Directory ;;
        4) Initialize_Repo ;;
        5) Setup_CCache ;;
        e) exit 0;;
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Install_Dependencies(){
    show_menus(){
    clear
    tput setaf 2
    echo "=================="
    echo "|  Dependencies  |"
    echo "=================="
    echo "| [1] Arch       |"
    echo "| [2] Ubuntu     |"
    echo "| [3] Exit       |" 
    echo "=================="
}
read_options(){
    local choice
    tput setaf 7; read -p "Enter choice [ 1 - 3] " choice
    case $choice in
        1) Arch ;;
        2) Ubuntu ;;
        e) exit 0;;
        *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}
Arch(){
        tput setaf 1; echo "Installing Dependencies for Arch"
        tput setaf 3; echo "Gettings Things Ready"
        tput setaf 2; sudo pacman -Syu
        tput setaf 3; echo "Installing Android Dependencies" && sleep 3
        tput setaf 2; sudo pacman -S  git gnupg flex bison gperf sdl wxgtk2 bash-completion \
        squashfs-tools curl ncurses zlib schedtool perl-switch zip \
        unzip libxslt python2-virtualenv bc rsync  \
        xml2 lzop pngcrush imagemagick jdk8-openjdk  jdk9-openjdk repo android-tools python-networkx 
        tput setaf 3; echo "Installing 64 bit Dependencies" && sleep 3
        tput setaf 2; sudo pacman -S ncurses5-compat-libs lib32-ncurses5-compat-libs lib32-zlib lib32-ncurses lib32-readline
        tput setaf 3; echo "Installing Extra Dependencies" && sleep 3
        tput setaf 2; sudo pacman -S ca-certificates-mozilla fakeroot make pkg-config maven tmux screen w3m ncftp yaourt
        tput setaf 2; yaourt -S neofetch aur/tilix 
        tput setaf 3; echo "Check & Reinstall Dependencies " && sleep 3
        tput setaf 2; sudo pacman -S base-devel
        tput setaf 3; echo "Disable PGP checking from AUR" && sleep 3
        export MAKEPKG="makepkg --skippgpcheck"
        tput setaf 2;
        yaourt -S libtinfo --noconfirm
        yaourt -S lib32-ncurses5-compat-libs --noconfirm
        yaourt -S ncurses5-compat-libs --noconfirm
        pause
        return
}
Ubuntu(){
         echo "Installing Dependencies for Ubuntu"
         sudo apt install neofetch tilix
         pause
         return
}
}
Setup_Google_Source(){
    echo "Setting up Google Source"
    mkdir ~/bin
    PATH=~/bin:$PATH
    curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
    pause
    return
}
Create_ROM_Directory(){
    echo "Creating ROM Directory:"
    echo "mkdir ~/ROM-Directory"
    pause
    mkdir ~/ROM-Directory
    pause
    return
}
Initialize_Repo(){
    echo "Initialize Repo:"
    echo "cd ~/ROM-Directory"
    pause
    cd ~/ROM-Directory
    echo "Example: repo init -u https://github.com/username/platform_manifest.git -b branch"
    pause
    echo "Initializing DirtyUnicorns"
    pause
    repo init -u https://github.com/DirtyUnicorns/android_manifest -b o8x
    return
}
Setup_CCache(){
    echo "export USE_CCACHE=1" >> ~/.bashrc
    echo "~/ROM-Directory/prebuilts/misc/linux-x86/ccache/ccache -M 60G"
    pause
    return
}
}

# ----------------------------------------------
# Trap CTRL+C, CTRL+Z and quit singles
# ----------------------------------------------
# trap '' SIGINT SIGQUIT SIGTSTP
 
# -----------------------------------
# Main logic - infinite loop
# ------------------------------------
while true
do
    show_menus
    read_options 
done