#!/bin/bash
#
# Copyright (C) 2017-2018 Matthew Keller
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

sudo pacman -Syu
sudo pacman -S openssh xclip
#ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
#eval "$(ssh-agent -s)"
#ssh-add ~/.ssh/id_rsa
#xclip -sel clip < ~/.ssh/id_rsa.pub
#Login to Github and Add SSH key

mkdir $HOME/Github && cd $HOME/Github && git clone git@github.com:KillerDroid96/Scripts.git
sudo cp ~/Github/Scripts/Files/sshd_config /etc/ssh/sshd_config
sudo cp ~/Github/Scripts/Linux/motd.sh /etc/profile.d
cp ~/Github/Scripts/Linux/.bashrc ~/
cp ~/Github/Scripts/Linux/banner ~/cp Github/Scripts/Files/neofetch ~/.config/neofetch/config
cd /etc/profile.d && touch ~/hushlogin && sudo chmod -R 755 motd.sh
