#!/bin/bash
#
# Copyright (C) 2017-2018 Matthew Keller
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# Dependencies: spotify and mpris-ctl
# Usage       : ./spotify next(nt) or prev(pt)


if [ "next || nt" ]; then
	mpris-ctl next
elif ["prev || pt"]; then
	mpris-ctl prev
fi

		  echsetto "==============================="
          echo "|            Spotify          |"
          echo "==============================="
mpris-ctl info "| Artist   : %artist_name"  
mpris-ctl info "| Track    : %track_name"
# mpris-ctl info "| Shuffle  : %shuffle"
mpris-ctl info "| Length   : %track_length"
          echo "==============================="